### ISSUE TITLE
Figure out what a "docker plugin" looks like

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox-ui#61]
THis issue is a good primer: https://github.com/kalabox/kalastack-docker/issues/29

ultimately i think we want something like (or exactly like?) what is used in fig a la

```
web:
  build: .
  command: python app.py
  links:
   - db
  ports:
   - "8000:8000"
db:
  image: postgres
```

Whatever we figure out here should be passed to the node mod in https://github.com/kalabox/kalabox/issues/60, the result of which should be containers spun up according to our plugin in the b2d VM.
